"""Add user mood

Revision ID: 752cacb5ae6a
Revises: 77718db325a8
Create Date: 2024-04-06 15:29:37.054043

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "752cacb5ae6a"
down_revision: Union[str, None] = "77718db325a8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    sa.Enum("SUN", "WIND", "RAIN", "THUNDER", "SNOW", name="usermood").create(op.get_bind())
    op.add_column(
        "user_user",
        sa.Column(
            "mood",
            postgresql.ENUM("SUN", "WIND", "RAIN", "THUNDER", "SNOW", name="usermood", create_type=False),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_user", "mood")
    sa.Enum("SUN", "WIND", "RAIN", "THUNDER", "SNOW", name="usermood").drop(op.get_bind())
    # ### end Alembic commands ###
