"""Update relation

Revision ID: 77718db325a8
Revises: 4a2b682a35aa
Create Date: 2024-04-03 22:20:17.331273

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "77718db325a8"
down_revision: Union[str, None] = "4a2b682a35aa"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_pair", sa.Column("main_user_id", sa.BigInteger(), nullable=False))
    op.drop_constraint("user_pair_user_id_fkey", "user_pair", type_="foreignkey")
    op.create_foreign_key(None, "user_pair", "user_user", ["main_user_id"], ["id"])
    op.drop_column("user_pair", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user_pair", sa.Column("user_id", sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, "user_pair", type_="foreignkey")
    op.create_foreign_key("user_pair_user_id_fkey", "user_pair", "user_user", ["user_id"], ["id"])
    op.drop_column("user_pair", "main_user_id")
    # ### end Alembic commands ###
