"""Adding user model

Revision ID: d339f1bb85c7
Revises:
Create Date: 2024-04-02 20:48:45.364817

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d339f1bb85c7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_user",
        sa.Column("phone_number", sa.String(), nullable=False),
        sa.Column("id", sa.BigInteger(), autoincrement=False, nullable=False),
        sa.Column("created", sa.DateTime(), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_user_id"), "user_user", ["id"], unique=True)
    op.create_index(op.f("ix_user_user_phone_number"), "user_user", ["phone_number"], unique=True)
    op.create_table(
        "user_pair",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("is_approved", sa.Boolean(), nullable=False),
        sa.Column("second_user_id", sa.BigInteger(), nullable=False),
        sa.ForeignKeyConstraint(
            ["second_user_id"],
            ["user_user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user_user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_pair_id"), "user_pair", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_pair_id"), table_name="user_pair")
    op.drop_table("user_pair")
    op.drop_index(op.f("ix_user_user_phone_number"), table_name="user_user")
    op.drop_index(op.f("ix_user_user_id"), table_name="user_user")
    op.drop_table("user_user")
    # ### end Alembic commands ###
